# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/blog.rb.tmpl in the blogtool repo.
class Blog < Formula
  desc "Single-binary static blog tool — posts, ideas, drafts, templates"
  homepage "https://github.com/simonski/blogtool"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.0/blog_0.1.0_darwin_arm64.tar.gz"
      sha256 "f37eb584536128f02e0702aecd3e845e67f6214bbe641c48fd92bd16dbab3816"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.0/blog_0.1.0_darwin_amd64.tar.gz"
      sha256 "b1dcd11c7e6cb814962a458108b1e26f42022362ef75bd7dd437d475f1faafb0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.0/blog_0.1.0_linux_arm64.tar.gz"
      sha256 "b7370b37149b50d0a1bd09e8ca814b00020a57e028a7c161f778facfc5bef4ae"
    end

    on_intel do
      url "https://github.com/simonski/homebrew-tap/releases/download/blogtool-v0.1.0/blog_0.1.0_linux_amd64.tar.gz"
      sha256 "5e356720013257d0458a26b0f387478086be30f662600cff75568f99922e2f1d"
    end
  end

  def install
    bin.install "blog"
  end

  test do
    assert_match "0.1.0", shell_output("#{bin}/blog version")
  end
end
